import { CEEProcess } from '@/types/installer';

export const mockCEEProcesses: CEEProcess[] = [
  {
    code: 'BAR-TH-171',
    name: 'Pompe à chaleur air/eau',
    description: 'Installation d\'une pompe à chaleur air/eau pour le chauffage et/ou la production d\'eau chaude sanitaire',
    category: 'residential',
    requiredDocuments: [
      {
        type: 'devis',
        name: 'Devis',
        requirement: 'required',
        description: 'Devis détaillé mentionnant la prime CEE, les caractéristiques de la PAC et les travaux à réaliser',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760, // 10MB
        allowMultiple: false,
      },
      {
        type: 'facture',
        name: 'Facture',
        requirement: 'required',
        description: 'Facture acquittée avec mention des équipements installés et de la main d\'œuvre',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'attestation_honneur',
        name: 'Attestation sur l\'honneur',
        requirement: 'required',
        description: 'Attestation sur l\'honneur signée par le bénéficiaire',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 5242880, // 5MB
        allowMultiple: false,
      },
      {
        type: 'cadre_contribution',
        name: 'Cadre de contribution',
        requirement: 'required',
        description: 'Document signé attestant de la contribution financière',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: false,
      },
      {
        type: 'photos',
        name: 'Photos de l\'installation',
        requirement: 'required',
        description: 'Photos de l\'équipement installé (plaque signalétique visible)',
        acceptedFormats: ['JPG', 'PNG', 'PDF'],
        maxSize: 5242880,
        allowMultiple: true,
      },
    ],
  },
  {
    code: 'BAR-TH-104',
    name: 'Fenêtre ou porte-fenêtre complète avec vitrage isolant',
    description: 'Remplacement de fenêtres simple vitrage par des fenêtres double ou triple vitrage',
    category: 'residential',
    requiredDocuments: [
      {
        type: 'devis',
        name: 'Devis',
        requirement: 'required',
        description: 'Devis détaillé avec caractéristiques techniques des menuiseries',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'facture',
        name: 'Facture',
        requirement: 'required',
        description: 'Facture acquittée mentionnant les performances des vitrages',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'attestation_honneur',
        name: 'Attestation sur l\'honneur',
        requirement: 'required',
        description: 'Attestation sur l\'honneur signée',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: false,
      },
      {
        type: 'photos',
        name: 'Photos',
        requirement: 'optional',
        description: 'Photos avant/après installation',
        acceptedFormats: ['JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: true,
      },
    ],
  },
  {
    code: 'BAR-TH-106',
    name: 'Chaudière individuelle à haute performance énergétique',
    description: 'Installation d\'une chaudière à condensation ou basse température',
    category: 'residential',
    requiredDocuments: [
      {
        type: 'devis',
        name: 'Devis',
        requirement: 'required',
        description: 'Devis avec caractéristiques de la chaudière',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'facture',
        name: 'Facture',
        requirement: 'required',
        description: 'Facture acquittée',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'attestation_honneur',
        name: 'Attestation sur l\'honneur',
        requirement: 'required',
        description: 'Attestation signée',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: false,
      },
      {
        type: 'photos',
        name: 'Photos',
        requirement: 'required',
        description: 'Photos de la chaudière installée',
        acceptedFormats: ['JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: true,
      },
    ],
  },
  {
    code: 'BAR-EN-101',
    name: 'Isolation de combles ou de toitures',
    description: 'Isolation thermique des combles perdus ou aménagés',
    category: 'residential',
    requiredDocuments: [
      {
        type: 'devis',
        name: 'Devis',
        requirement: 'required',
        description: 'Devis détaillé avec surface et résistance thermique',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'facture',
        name: 'Facture',
        requirement: 'required',
        description: 'Facture acquittée',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'attestation_honneur',
        name: 'Attestation sur l\'honneur',
        requirement: 'required',
        description: 'Attestation signée',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: false,
      },
      {
        type: 'photos',
        name: 'Photos',
        requirement: 'required',
        description: 'Photos avant et après travaux',
        acceptedFormats: ['JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: true,
      },
    ],
  },
  {
    code: 'BAR-TH-127',
    name: 'Ventilation mécanique contrôlée double flux',
    description: 'Installation d\'un système VMC double flux',
    category: 'residential',
    requiredDocuments: [
      {
        type: 'devis',
        name: 'Devis',
        requirement: 'required',
        description: 'Devis avec caractéristiques du système VMC',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'facture',
        name: 'Facture',
        requirement: 'required',
        description: 'Facture acquittée',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 10485760,
        allowMultiple: false,
      },
      {
        type: 'attestation_honneur',
        name: 'Attestation sur l\'honneur',
        requirement: 'required',
        description: 'Attestation signée',
        acceptedFormats: ['PDF', 'JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: false,
      },
      {
        type: 'photos',
        name: 'Photos',
        requirement: 'optional',
        description: 'Photos de l\'installation',
        acceptedFormats: ['JPG', 'PNG'],
        maxSize: 5242880,
        allowMultiple: true,
      },
    ],
  },
];