import { ValidationField, ValidationRule, PDFDocument } from '@/types/validation';

export const mockPDFDocuments: PDFDocument[] = [
  {
    id: 'doc-1',
    type: 'devis',
    displayName: 'Devis',
    filename: 'Devis.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pageCount: 2,
    confidence: 95,
    processingStatus: 'completed',
  },
  {
    id: 'doc-2',
    type: 'facture',
    displayName: 'Facture',
    filename: 'Facture.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pageCount: 1,
    confidence: 98,
    processingStatus: 'completed',
  },
  {
    id: 'doc-3',
    type: 'attestation_honneur',
    displayName: 'Attestation Honneur',
    filename: 'AH.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pageCount: 1,
    confidence: 97,
    processingStatus: 'completed',
  },
  {
    id: 'doc-4',
    type: 'cadre_contribution',
    displayName: 'Cadre Contribution',
    filename: 'CC.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pageCount: 1,
    confidence: 96,
    processingStatus: 'completed',
  },
  {
    id: 'doc-5',
    type: 'photos',
    displayName: 'Photos',
    filename: 'Photos.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pageCount: 3,
    confidence: 92,
    processingStatus: 'completed',
  },
];

export const mockValidationFields: ValidationField[] = [
  // Devis fields
  {
    id: 'field-1',
    documentType: 'devis',
    fieldName: 'numero_devis',
    displayName: 'Numéro devis',
    value: '2024-BADJI-171',
    confidence: 98,
    status: 'unreviewed',
    validationRule: {
      name: 'Format numéro devis',
      description: 'Vérifie que le numéro de devis respecte le format attendu (YYYY-XXX-NNN)',
      status: 'passed',
      message: 'Format valide détecté',
    },
  },
  {
    id: 'field-2',
    documentType: 'devis',
    fieldName: 'date_devis',
    displayName: 'Date devis',
    value: '18/10/2024',
    confidence: 99,
    status: 'unreviewed',
    validationRule: {
      name: 'Date devis antérieure à la facture',
      description: 'La date du devis doit être antérieure à la date de la facture',
      status: 'passed',
      message: 'Date cohérente avec la facture du 20/11/2024',
    },
  },
  {
    id: 'field-3',
    documentType: 'devis',
    fieldName: 'beneficiaire_nom',
    displayName: 'Bénéficiaire nom',
    value: 'BADJI Mehenna',
    confidence: 97,
    status: 'unreviewed',
    validationRule: {
      name: 'Cohérence nom bénéficiaire',
      description: 'Le nom du bénéficiaire doit être identique sur tous les documents',
      status: 'passed',
      message: 'Nom identique sur Devis, Facture et AH',
    },
  },
  {
    id: 'field-4',
    documentType: 'devis',
    fieldName: 'prime_cee',
    displayName: 'Prime CEE',
    value: '4,000.00 €',
    confidence: 99,
    status: 'unreviewed',
    validationRule: {
      name: 'Cohérence Prime CEE',
      description: 'Le montant de la prime CEE doit être identique sur le devis, la facture et le CDC',
      status: 'passed',
      message: 'Montant identique sur tous les documents (4,000.00 €)',
    },
  },
  {
    id: 'field-5',
    documentType: 'devis',
    fieldName: 'signature_presente',
    displayName: 'Signature présente',
    value: 'Oui',
    confidence: 95,
    status: 'unreviewed',
    validationRule: {
      name: 'Présence signature devis',
      description: 'Le devis doit comporter la signature du bénéficiaire avec mention "Bon pour accord"',
      status: 'warning',
      message: 'Signature détectée mais mention "Bon pour accord" peu lisible',
    },
  },
  // Facture fields
  {
    id: 'field-6',
    documentType: 'facture',
    fieldName: 'numero_facture',
    displayName: 'Numéro facture',
    value: 'FACT-2024-5678',
    confidence: 97,
    status: 'unreviewed',
    validationRule: {
      name: 'Format numéro facture',
      description: 'Vérifie que le numéro de facture respecte le format attendu',
      status: 'passed',
      message: 'Format valide détecté',
    },
  },
  {
    id: 'field-7',
    documentType: 'facture',
    fieldName: 'date_facture',
    displayName: 'Date facture',
    value: '20/11/2024',
    confidence: 99,
    status: 'unreviewed',
    validationRule: {
      name: 'Date facture postérieure au devis',
      description: 'La date de la facture doit être postérieure à la date du devis',
      status: 'passed',
      message: 'Date cohérente (33 jours après le devis)',
    },
  },
  {
    id: 'field-8',
    documentType: 'facture',
    fieldName: 'montant_ttc',
    displayName: 'Montant total TTC',
    value: '8,750.00 €',
    confidence: 98,
    status: 'unreviewed',
    validationRule: {
      name: 'Cohérence montant TTC',
      description: 'Le montant TTC doit correspondre au devis signé',
      status: 'passed',
      message: 'Montant identique au devis',
    },
  },
  // Attestation Honneur fields
  {
    id: 'field-9',
    documentType: 'attestation_honneur',
    fieldName: 'date_engagement',
    displayName: 'Date engagement',
    value: '15/10/2024',
    confidence: 96,
    status: 'unreviewed',
    validationRule: {
      name: 'Date engagement antérieure aux travaux',
      description: 'La date d\'engagement doit être antérieure à la date de début des travaux',
      status: 'warning',
      message: 'Délai de 12 jours détecté, proche de la limite de 14 jours',
    },
  },
  {
    id: 'field-10',
    documentType: 'attestation_honneur',
    fieldName: 'signature_beneficiaire',
    displayName: 'Signature bénéficiaire',
    value: 'Oui',
    confidence: 94,
    status: 'unreviewed',
    validationRule: {
      name: 'Cohérence signature bénéficiaire',
      description: 'La signature doit correspondre à celle présente sur le devis',
      status: 'warning',
      message: 'Légère différence détectée avec la signature du devis',
    },
  },
  // Cadre Contribution fields
  {
    id: 'field-11',
    documentType: 'cadre_contribution',
    fieldName: 'montant_prime',
    displayName: 'Montant prime',
    value: '4,000.00 €',
    confidence: 98,
    status: 'unreviewed',
    validationRule: {
      name: 'Cohérence montant CDC',
      description: 'Le montant sur le CDC doit correspondre à la prime CEE du devis et de la facture',
      status: 'passed',
      message: 'Montant identique sur tous les documents',
    },
  },
  {
    id: 'field-12',
    documentType: 'cadre_contribution',
    fieldName: 'signature_installateur',
    displayName: 'Signature installateur',
    value: 'Oui',
    confidence: 96,
    status: 'unreviewed',
    validationRule: {
      name: 'Présence signature installateur',
      description: 'Le CDC doit comporter la signature de l\'installateur RGE',
      status: 'passed',
      message: 'Signature installateur détectée et validée',
    },
  },
  // Photos fields
  {
    id: 'field-13',
    documentType: 'photos',
    fieldName: 'photo_equipement',
    displayName: 'Photo équipement',
    value: 'Présente',
    confidence: 92,
    status: 'unreviewed',
    validationRule: {
      name: 'Présence photo équipement',
      description: 'Une photo de l\'équipement installé doit être fournie',
      status: 'passed',
      message: 'Photo équipement détectée',
    },
  },
  {
    id: 'field-14',
    documentType: 'photos',
    fieldName: 'photo_plaque',
    displayName: 'Photo plaque signalétique',
    value: 'Présente',
    confidence: 88,
    status: 'unreviewed',
    validationRule: {
      name: 'Lisibilité plaque signalétique',
      description: 'La plaque signalétique doit être lisible et correspondre aux spécifications',
      status: 'warning',
      message: 'Plaque détectée mais lisibilité partielle',
    },
  },
];

export const mockValidationRulesForDossier: ValidationRule[] = [
  {
    id: 'rule-1',
    code: 'VAL-001',
    name: 'Date engagement antérieure aux travaux',
    description: 'La date d\'engagement doit être antérieure à la date des travaux',
    status: 'passed',
    canOverride: false,
  },
  {
    id: 'rule-2',
    code: 'VAL-002',
    name: 'Prime CEE cohérente sur tous les documents',
    description: 'Le montant de la prime CEE doit être identique sur le devis et la facture',
    status: 'passed',
    canOverride: false,
  },
  {
    id: 'rule-3',
    code: 'VAL-003',
    name: 'Adresse travaux identique',
    description: 'L\'adresse des travaux doit être identique sur tous les documents',
    status: 'passed',
    canOverride: false,
  },
  {
    id: 'rule-4',
    code: 'VAL-004',
    name: 'Délai entre engagement et travaux < 14 jours (12 jours)',
    description: 'Le délai entre la date d\'engagement et la date de début des travaux ne doit pas dépasser 14 jours',
    status: 'warning',
    message: 'Délai de 12 jours détecté, proche de la limite',
    canOverride: true,
  },
  {
    id: 'rule-5',
    code: 'VAL-005',
    name: 'Signature AH partie B légèrement différente du devis',
    description: 'La signature sur l\'attestation honneur doit correspondre à celle du devis',
    status: 'warning',
    message: 'Légère différence détectée entre les signatures',
    canOverride: true,
  },
];