"""Initial migration

Revision ID: 7a50fcad6210
Revises: 001
Create Date: 2025-12-01 15:01:59.370005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a50fcad6210'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('api_endpoint', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_configurations_config_key'), 'ai_configurations', ['config_key'], unique=True)
    op.create_index(op.f('ix_ai_configurations_id'), 'ai_configurations', ['id'], unique=False)
    op.create_table('field_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('validation_pattern', sa.String(length=255), nullable=True),
    sa.Column('extraction_hints', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_schemas_id'), 'field_schemas', ['id'], unique=False)
    op.create_table('model_performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_metrics_id'), 'model_performance_metrics', ['id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_coup_de_pouce', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_code'), 'processes', ['code'], unique=True)
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('installers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('rge_number', sa.String(length=50), nullable=True),
    sa.Column('rge_valid_until', sa.Date(), nullable=True),
    sa.Column('rge_status', sa.String(length=20), nullable=False),
    sa.Column('qualifications', sa.JSON(), nullable=False),
    sa.Column('contract_reference', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installers_id'), 'installers', ['id'], unique=False)
    op.create_index(op.f('ix_installers_siret'), 'installers', ['siret'], unique=True)
    op.create_table('validation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('process_id', sa.UUID(), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('can_override', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_code'), 'validation_rules', ['code'], unique=True)
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('installer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_validator_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'AWAITING_REVIEW', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED', name='dossierstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='priority'), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=False),
    sa.Column('beneficiary_address', sa.String(), nullable=False),
    sa.Column('beneficiary_city', sa.String(length=255), nullable=False),
    sa.Column('beneficiary_postal_code', sa.String(length=10), nullable=False),
    sa.Column('beneficiary_email', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_phone', sa.String(length=20), nullable=True),
    sa.Column('precarity_status', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_validator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_id'), 'dossiers', ['id'], unique=False)
    op.create_index(op.f('ix_dossiers_reference'), 'dossiers', ['reference'], unique=True)
    op.create_index(op.f('ix_dossiers_status'), 'dossiers', ['status'], unique=False)
    op.create_index(op.f('ix_dossiers_submitted_at'), 'dossiers', ['submitted_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'CLASSIFYING', 'CLASSIFIED', 'EXTRACTING', 'EXTRACTED', 'VALIDATING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('classification_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_dossier_id'), 'documents', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('installer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('kwh_cumac', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_per_kwh', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_on_validation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_on_emmy', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('affected_fields', sa.JSON(), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_dossier_id'), 'validation_results', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('field_schema_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('extracted_value', sa.JSON(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.Enum('UNREVIEWED', 'CONFIRMED', 'CORRECTED', 'MARKED_WRONG', name='fieldstatus'), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=True),
    sa.Column('corrected_value', sa.JSON(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('marked_wrong_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_wrong_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_schema_id'], ['field_schemas.id'], ),
    sa.ForeignKeyConstraint(['marked_wrong_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_dossier_id'), 'extracted_fields', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_id'), 'extracted_fields', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_status'), 'extracted_fields', ['status'], unique=False)
    op.create_table('human_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('extracted_field_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=True),
    sa.Column('corrected_value', sa.JSON(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_before', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('validator_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=False),
    sa.Column('training_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_fields.id'], ),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_feedback_created_at'), 'human_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_human_feedback_id'), 'human_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_human_feedback_used_for_training'), 'human_feedback', ['used_for_training'], unique=False)
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_rule_results_id', table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_index('ix_rules_id', table_name='rules')
    op.drop_index('ix_rules_name', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_submission_files_id', table_name='submission_files')
    op.drop_table('submission_files')
    op.drop_index('ix_extracted_data_id', table_name='extracted_data')
    op.drop_table('extracted_data')
    op.drop_index('ix_schemas_id', table_name='schemas')
    op.drop_index('ix_schemas_name', table_name='schemas')
    op.drop_table('schemas')
    op.drop_index('ix_submissions_id', table_name='submissions')
    op.drop_table('submissions')
    op.add_column('document_types', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('document_types', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('document_types', sa.Column('extraction_schema_id', sa.UUID(), nullable=True))
    op.add_column('document_types', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('document_types', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint('document_types_name_key', 'document_types', type_='unique')
    op.drop_index('ix_document_types_name', table_name='document_types')
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=True)
    op.drop_constraint('document_types_created_by_fkey', 'document_types', type_='foreignkey')
    op.create_foreign_key(None, 'document_types', 'field_schemas', ['extraction_schema_id'], ['id'])
    op.drop_column('document_types', 'created_by')
    op.drop_column('document_types', 'required_pdf_count')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'active')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password_hash')
    op.add_column('document_types', sa.Column('required_pdf_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('document_types', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_types', type_='foreignkey')
    op.create_foreign_key('document_types_created_by_fkey', 'document_types', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.create_index('ix_document_types_name', 'document_types', ['name'], unique=False)
    op.create_unique_constraint('document_types_name_key', 'document_types', ['name'])
    op.alter_column('document_types', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('document_types', 'is_active')
    op.drop_column('document_types', 'extraction_schema_id')
    op.drop_column('document_types', 'category')
    op.drop_column('document_types', 'code')
    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('submissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('installer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'UPLOADED', 'EXTRACTING', 'EXTRACTED', 'VALIDATING', 'APPROVED', 'REJECTED', name='submissionstatus'), server_default=sa.text("'PENDING'::submissionstatus"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name='submissions_document_type_id_fkey'),
    sa.ForeignKeyConstraint(['installer_id'], ['users.id'], name='submissions_installer_id_fkey'),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], name='submissions_validator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='submissions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_submissions_id', 'submissions', ['id'], unique=False)
    op.create_table('schemas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extraction_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='schemas_created_by_fkey'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name='schemas_document_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='schemas_pkey')
    )
    op.create_index('ix_schemas_name', 'schemas', ['name'], unique=False)
    op.create_index('ix_schemas_id', 'schemas', ['id'], unique=False)
    op.create_table('extracted_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extracted_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_edited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('edited_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name='extracted_data_edited_by_fkey'),
    sa.ForeignKeyConstraint(['file_id'], ['submission_files.id'], name='extracted_data_file_id_fkey'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name='extracted_data_submission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='extracted_data_pkey')
    )
    op.create_index('ix_extracted_data_id', 'extracted_data', ['id'], unique=False)
    op.create_table('submission_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), server_default=sa.text("'application/pdf'::character varying"), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name='submission_files_submission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='submission_files_pkey')
    )
    op.create_index('ix_submission_files_id', 'submission_files', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('rules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='rules_created_by_fkey'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name='rules_document_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_rules_name', 'rules', ['name'], unique=False)
    op.create_index('ix_rules_id', 'rules', ['id'], unique=False)
    op.create_table('rule_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name='rule_results_rule_id_fkey'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name='rule_results_submission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rule_results_pkey')
    )
    op.create_index('ix_rule_results_id', 'rule_results', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.drop_index(op.f('ix_human_feedback_used_for_training'), table_name='human_feedback')
    op.drop_index(op.f('ix_human_feedback_id'), table_name='human_feedback')
    op.drop_index(op.f('ix_human_feedback_created_at'), table_name='human_feedback')
    op.drop_table('human_feedback')
    op.drop_index(op.f('ix_extracted_fields_status'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_dossier_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_dossier_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_dossier_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dossiers_submitted_at'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_status'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_reference'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_id'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_code'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_installers_siret'), table_name='installers')
    op.drop_index(op.f('ix_installers_id'), table_name='installers')
    op.drop_table('installers')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index('idx_activity_logs_entity', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_code'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_model_performance_metrics_id'), table_name='model_performance_metrics')
    op.drop_table('model_performance_metrics')
    op.drop_index(op.f('ix_field_schemas_id'), table_name='field_schemas')
    op.drop_table('field_schemas')
    op.drop_index(op.f('ix_ai_configurations_id'), table_name='ai_configurations')
    op.drop_index(op.f('ix_ai_configurations_config_key'), table_name='ai_configurations')
    op.drop_table('ai_configurations')
    # ### end Alembic commands ###

